import "./globals.css";
import "@mantine/core/styles.css";
import { MantineProvider, ColorSchemeScript, AppShell } from "@mantine/core";
import { theme } from "@/theme";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider withGlobalStyles withNormalizeCSS theme={theme}>
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
