import "./globals.css";
import "@mantine/core/styles.css";
import { MantineProvider, ColorSchemeScript, AppShell } from "@mantine/core";
import Navbar from "./components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider>
          <AppShell navbar={{ width: 96 }} padding="md">
            <Navbar children={children} />
          </AppShell>
        </MantineProvider>
      </body>
    </html>
  );
}
